[versions]
kotlin = "2.0.20"
kotest = "5.9.1"

[libraries]
khttpclient = "work.socialhub:khttpclient:0.0.1-SNAPSHOT"
ktor-core = "io.ktor:ktor-client-core:2.3.12"
datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.6.1"
coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0"
serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"
serialization-cbor = "org.jetbrains.kotlinx:kotlinx-serialization-cbor:1.7.3"
kotest-junit5 = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
nexus-publish = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin:2.0.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
vanniktech-maven-publish = "com.vanniktech.maven.publish:0.29.0"
dokka = "org.jetbrains.dokka:1.9.20"