name: Publish Package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        target:
          - core
          - stream
    env:
      RUN_TARGET: ${{ matrix.target }}

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
        ./gradlew ${RUN_TARGET}:build -x core:jvmTest

    - name: Publish to Repsy
      run: |
        ./gradlew ${RUN_TARGET}:publish -x core:jvmTest