name: Publish RELEASE Package

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        include:
          - target: publishIosArm64PublicationToSonatypeRepository
            os: macos-latest
          - target: publishJvmPublicationToSonatypeRepository
            os: ubuntu-latest
          - target: publishKotlinMultiplatformPublicationToSonatypeRepository
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle publish
        run: |
          ./gradlew
          ${{ matrix.target }}
          closeSonatypeStagingRepository
          -Psigning.gnupg.passphrase='${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}'
          -Psigning.gnupg.keyName='${{secrets.OSSRH_GPG_SECRET_KEY_ID}}'
          -PsonatypeUsername='${{secrets.OSSRH_USERNAME}}'
          -PsonatypePassword='${{secrets.OSSRH_PASSWORD}}'